package com.reciperoulette.util

import android.content.Context
import android.content.Intent
import com.reciperoulette.data.RecipeResult

object ShareUtils {

    /**
     * Opens the Android share sheet with the recipe formatted as readable text.
     */
    fun shareRecipe(context: Context, recipe: RecipeResult) {
        val text = buildString {
            appendLine("🍽️ ${recipe.recipeName}")
            appendLine()
            appendLine("🥬 Ingredients used:")
            recipe.selectedIngredients.forEach { appendLine("  • $it") }
            appendLine()
            appendLine("👨‍🍳 Steps:")
            recipe.steps.forEachIndexed { index, step ->
                appendLine("  ${index + 1}. $step")
            }
            appendLine()
            appendLine("💡 Chef's tip: ${recipe.chefTip}")
            appendLine()
            appendLine("Generated by Recipe Roulette 🎲")
        }

        val intent = Intent(Intent.ACTION_SEND).apply {
            type = "text/plain"
            putExtra(Intent.EXTRA_SUBJECT, recipe.recipeName)
            putExtra(Intent.EXTRA_TEXT, text)
        }
        context.startActivity(Intent.createChooser(intent, "Share Recipe"))
    }
}
